### ISSUE TITLE
Redesign docs

### ISSUE THREAD

**Issue by waymobetta** [ChainSafe/chainbridge-docs#32]
## Implementation details

@taha-be Can you take a shot at redesigning this main page with your vision? 

Core [ToC](https://github.com/ChainSafe/chainbridge-core/blob/main/README.md#table-of-contents) includes additional documentation that can be migrated in to the gitbook page via integrations (branch: main).

**currently:**
- [x] markdown syntax needs spacing in some places (screenshot 1.)
- [ ] landing page linked to [main](https://chainbridge-docs.chainsafe.io/#overview), perhaps should link somewhere else, like not to the v1 chainbridge but to the core instead: (screenshot 2.)
- [x] some directories are lowercased and this looks unprofessional (screenshot 3.)
- [ ] general layout redesign for ease of use/clarity

**Screenshots:**

## 1.

<img width="966" alt="Screen Shot 2021-10-01 at 9 57 16 AM" src="https://user-images.githubusercontent.com/17755587/135659197-0af8563e-3656-43a5-9cf8-13ed6ad48789.png">

## 2.

<img width="299" alt="Screen Shot 2021-10-01 at 9 58 07 AM" src="https://user-images.githubusercontent.com/17755587/135659300-176d7ebb-c663-4f2f-8e9a-8beecc0d08dd.png">

## 3.

<img width="289" alt="Screen Shot 2021-10-01 at 10 01 27 AM" src="https://user-images.githubusercontent.com/17755587/135659414-54fefcc0-39e9-46a4-bfb8-b12ff1493ce9.png">

**Comment by waymobetta** [comment]
@taha-be any update on this?

Perhaps we can meet to discuss a game plan

**Comment by P1sar** [comment]
Closing this due to being to way abstract. Tasks related to documentation will be mostly located under management dashboard in Notion
